title: CFC Servers Developer Program
author: CFC Servers
email: contact@cfcservers.org
description: CFC Servers Developer Program Summary
baseurl: "/"
url: ""

plugins:
  - jekyll-feed
  - jekyll-menus
